{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting labelme\n",
      "  Using cached labelme-5.4.1-py3-none-any.whl\n",
      "Requirement already satisfied: tensorflow in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (2.16.1)\n",
      "Collecting tensorflow-gpu\n",
      "  Using cached tensorflow-gpu-2.12.0.tar.gz (2.6 kB)\n",
      "  Preparing metadata (setup.py) ... \u001b[?25ldone\n",
      "\u001b[?25hRequirement already satisfied: opencv-python in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (4.9.0.80)\n",
      "Requirement already satisfied: matplotlib in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (3.8.4)\n",
      "Collecting albumentations\n",
      "  Using cached albumentations-1.4.4-py3-none-any.whl (150 kB)\n",
      "Requirement already satisfied: Pillow>=2.8 in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (from labelme) (10.3.0)\n",
      "Collecting qtpy!=1.11.2\n",
      "  Using cached QtPy-2.4.1-py3-none-any.whl (93 kB)\n",
      "Collecting imgviz>=1.7.5\n",
      "  Using cached imgviz-1.7.5-py3-none-any.whl\n",
      "Collecting natsort>=7.1.0\n",
      "  Using cached natsort-8.4.0-py3-none-any.whl (38 kB)\n",
      "Requirement already satisfied: termcolor in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (from labelme) (2.4.0)\n",
      "Collecting PyQt5!=5.15.3,!=5.15.4\n",
      "  Using cached PyQt5-5.15.10-cp37-abi3-macosx_11_0_arm64.whl (6.6 MB)\n",
      "Collecting PyYAML\n",
      "  Using cached PyYAML-6.0.1-cp310-cp310-macosx_11_0_arm64.whl (169 kB)\n",
      "Collecting onnxruntime!=1.16.0,>=1.14.1\n",
      "  Using cached onnxruntime-1.17.3-cp310-cp310-macosx_11_0_universal2.whl (14.8 MB)\n",
      "Collecting scikit-image\n",
      "  Using cached scikit_image-0.23.2-cp310-cp310-macosx_12_0_arm64.whl (13.3 MB)\n",
      "Requirement already satisfied: numpy in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (from labelme) (1.26.4)\n",
      "Requirement already satisfied: gdown in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (from labelme) (5.1.0)\n",
      "Requirement already satisfied: keras>=3.0.0 in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (from tensorflow) (3.2.1)\n",
      "Requirement already satisfied: flatbuffers>=23.5.26 in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (from tensorflow) (24.3.25)\n",
      "Requirement already satisfied: h5py>=3.10.0 in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (from tensorflow) (3.11.0)\n",
      "Requirement already satisfied: astunparse>=1.6.0 in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (from tensorflow) (1.6.3)\n",
      "Requirement already satisfied: requests<3,>=2.21.0 in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (from tensorflow) (2.31.0)\n",
      "Requirement already satisfied: tensorboard<2.17,>=2.16 in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (from tensorflow) (2.16.2)\n",
      "Requirement already satisfied: typing-extensions>=3.6.6 in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (from tensorflow) (4.11.0)\n",
      "Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (from tensorflow) (0.36.0)\n",
      "Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (from tensorflow) (0.5.4)\n",
      "Requirement already satisfied: six>=1.12.0 in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (from tensorflow) (1.16.0)\n",
      "Requirement already satisfied: opt-einsum>=2.3.2 in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (from tensorflow) (3.3.0)\n",
      "Requirement already satisfied: google-pasta>=0.1.1 in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (from tensorflow) (0.2.0)\n",
      "Requirement already satisfied: wrapt>=1.11.0 in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (from tensorflow) (1.16.0)\n",
      "Requirement already satisfied: libclang>=13.0.0 in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (from tensorflow) (18.1.1)\n",
      "Requirement already satisfied: packaging in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (from tensorflow) (24.0)\n",
      "Requirement already satisfied: setuptools in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (from tensorflow) (65.5.0)\n",
      "Requirement already satisfied: absl-py>=1.0.0 in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (from tensorflow) (2.1.0)\n",
      "Requirement already satisfied: grpcio<2.0,>=1.24.3 in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (from tensorflow) (1.62.2)\n",
      "Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (from tensorflow) (4.25.3)\n",
      "Requirement already satisfied: ml-dtypes~=0.3.1 in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (from tensorflow) (0.3.2)\n",
      "Requirement already satisfied: python_version>\"3.7\" in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (from tensorflow-gpu) (0.0.2)\n",
      "Requirement already satisfied: fonttools>=4.22.0 in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (from matplotlib) (4.51.0)\n",
      "Requirement already satisfied: kiwisolver>=1.3.1 in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (from matplotlib) (1.4.5)\n",
      "Requirement already satisfied: python-dateutil>=2.7 in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (from matplotlib) (2.9.0.post0)\n",
      "Requirement already satisfied: contourpy>=1.0.1 in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (from matplotlib) (1.2.1)\n",
      "Requirement already satisfied: cycler>=0.10 in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (from matplotlib) (0.12.1)\n",
      "Requirement already satisfied: pyparsing>=2.3.1 in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (from matplotlib) (3.1.2)\n",
      "Collecting opencv-python-headless>=4.9.0\n",
      "  Using cached opencv_python_headless-4.9.0.80-cp37-abi3-macosx_11_0_arm64.whl (35.4 MB)\n",
      "Collecting scikit-learn>=1.3.2\n",
      "  Using cached scikit_learn-1.4.2-cp310-cp310-macosx_12_0_arm64.whl (10.4 MB)\n",
      "Collecting scipy>=1.10.0\n",
      "  Using cached scipy-1.13.0-cp310-cp310-macosx_12_0_arm64.whl (30.3 MB)\n",
      "Collecting pydantic>=2.6.4\n",
      "  Using cached pydantic-2.7.0-py3-none-any.whl (407 kB)\n",
      "Requirement already satisfied: wheel<1.0,>=0.23.0 in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (from astunparse>=1.6.0->tensorflow) (0.43.0)\n",
      "Requirement already satisfied: optree in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (from keras>=3.0.0->tensorflow) (0.11.0)\n",
      "Requirement already satisfied: namex in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (from keras>=3.0.0->tensorflow) (0.0.8)\n",
      "Requirement already satisfied: rich in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (from keras>=3.0.0->tensorflow) (13.7.1)\n",
      "Collecting coloredlogs\n",
      "  Using cached coloredlogs-15.0.1-py2.py3-none-any.whl (46 kB)\n",
      "Collecting sympy\n",
      "  Using cached sympy-1.12-py3-none-any.whl (5.7 MB)\n",
      "Collecting annotated-types>=0.4.0\n",
      "  Using cached annotated_types-0.6.0-py3-none-any.whl (12 kB)\n",
      "Collecting pydantic-core==2.18.1\n",
      "  Using cached pydantic_core-2.18.1-cp310-cp310-macosx_11_0_arm64.whl (1.8 MB)\n",
      "Requirement already satisfied: PyQt5-Qt5>=5.15.2 in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (from PyQt5!=5.15.3,!=5.15.4->labelme) (5.15.13)\n",
      "Collecting PyQt5-sip<13,>=12.13\n",
      "  Using cached PyQt5_sip-12.13.0-cp310-cp310-macosx_10_9_universal2.whl (144 kB)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (from requests<3,>=2.21.0->tensorflow) (3.7)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (from requests<3,>=2.21.0->tensorflow) (3.3.2)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (from requests<3,>=2.21.0->tensorflow) (2024.2.2)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (from requests<3,>=2.21.0->tensorflow) (2.2.1)\n",
      "Requirement already satisfied: tifffile>=2022.8.12 in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (from scikit-image->labelme) (2024.4.18)\n",
      "Collecting networkx>=2.8\n",
      "  Using cached networkx-3.3-py3-none-any.whl (1.7 MB)\n",
      "Collecting lazy-loader>=0.4\n",
      "  Using cached lazy_loader-0.4-py3-none-any.whl (12 kB)\n",
      "Collecting imageio>=2.33\n",
      "  Using cached imageio-2.34.0-py3-none-any.whl (313 kB)\n",
      "Collecting joblib>=1.2.0\n",
      "  Using cached joblib-1.4.0-py3-none-any.whl (301 kB)\n",
      "Requirement already satisfied: threadpoolctl>=2.0.0 in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (from scikit-learn>=1.3.2->albumentations) (3.4.0)\n",
      "Requirement already satisfied: markdown>=2.6.8 in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (from tensorboard<2.17,>=2.16->tensorflow) (3.6)\n",
      "Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (from tensorboard<2.17,>=2.16->tensorflow) (0.7.2)\n",
      "Requirement already satisfied: werkzeug>=1.0.1 in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (from tensorboard<2.17,>=2.16->tensorflow) (3.0.2)\n",
      "Requirement already satisfied: beautifulsoup4 in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (from gdown->labelme) (4.12.3)\n",
      "Requirement already satisfied: tqdm in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (from gdown->labelme) (4.66.2)\n",
      "Requirement already satisfied: filelock in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (from gdown->labelme) (3.13.4)\n",
      "Requirement already satisfied: MarkupSafe>=2.1.1 in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (from werkzeug>=1.0.1->tensorboard<2.17,>=2.16->tensorflow) (2.1.5)\n",
      "Requirement already satisfied: soupsieve>1.2 in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (from beautifulsoup4->gdown->labelme) (2.5)\n",
      "Collecting humanfriendly>=9.1\n",
      "  Using cached humanfriendly-10.0-py2.py3-none-any.whl (86 kB)\n",
      "Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (from requests<3,>=2.21.0->tensorflow) (1.7.1)\n",
      "Requirement already satisfied: markdown-it-py>=2.2.0 in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (from rich->keras>=3.0.0->tensorflow) (3.0.0)\n",
      "Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (from rich->keras>=3.0.0->tensorflow) (2.17.2)\n",
      "Requirement already satisfied: mpmath>=0.19 in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (from sympy->onnxruntime!=1.16.0,>=1.14.1->labelme) (1.3.0)\n",
      "Requirement already satisfied: mdurl~=0.1 in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.0.0->tensorflow) (0.1.2)\n",
      "Building wheels for collected packages: tensorflow-gpu\n",
      "  Building wheel for tensorflow-gpu (setup.py) ... \u001b[?25lerror\n",
      "  \u001b[1;31merror\u001b[0m: \u001b[1msubprocess-exited-with-error\u001b[0m\n",
      "  \n",
      "  \u001b[31m×\u001b[0m \u001b[32mpython setup.py bdist_wheel\u001b[0m did not run successfully.\n",
      "  \u001b[31m│\u001b[0m exit code: \u001b[1;36m1\u001b[0m\n",
      "  \u001b[31m╰─>\u001b[0m \u001b[31m[18 lines of output]\u001b[0m\n",
      "  \u001b[31m   \u001b[0m Traceback (most recent call last):\n",
      "  \u001b[31m   \u001b[0m   File \"<string>\", line 2, in <module>\n",
      "  \u001b[31m   \u001b[0m   File \"<pip-setuptools-caller>\", line 34, in <module>\n",
      "  \u001b[31m   \u001b[0m   File \"/private/var/folders/13/3pzxxwtd6cbdvdzq_lc6112r0000gn/T/pip-install-_m62r8yt/tensorflow-gpu_022857d31281414887364a2ec393f1e8/setup.py\", line 37, in <module>\n",
      "  \u001b[31m   \u001b[0m     raise Exception(TF_REMOVAL_WARNING)\n",
      "  \u001b[31m   \u001b[0m Exception:\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m =========================================================\n",
      "  \u001b[31m   \u001b[0m The \"tensorflow-gpu\" package has been removed!\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m Please install \"tensorflow\" instead.\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m Other than the name, the two packages have been identical\n",
      "  \u001b[31m   \u001b[0m since TensorFlow 2.1, or roughly since Sep 2019. For more\n",
      "  \u001b[31m   \u001b[0m information, see: pypi.org/project/tensorflow-gpu\n",
      "  \u001b[31m   \u001b[0m =========================================================\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m \u001b[31m[end of output]\u001b[0m\n",
      "  \n",
      "  \u001b[1;35mnote\u001b[0m: This error originates from a subprocess, and is likely not a problem with pip.\n",
      "\u001b[31m  ERROR: Failed building wheel for tensorflow-gpu\u001b[0m\u001b[31m\n",
      "\u001b[0m\u001b[?25h  Running setup.py clean for tensorflow-gpu\n",
      "Failed to build tensorflow-gpu\n",
      "Installing collected packages: tensorflow-gpu, sympy, scipy, qtpy, PyYAML, PyQt5-sip, pydantic-core, opencv-python-headless, networkx, natsort, lazy-loader, joblib, imageio, humanfriendly, annotated-types, scikit-learn, scikit-image, PyQt5, pydantic, coloredlogs, onnxruntime, imgviz, albumentations, labelme\n",
      "  Running setup.py install for tensorflow-gpu ... \u001b[?25lerror\n",
      "  \u001b[1;31merror\u001b[0m: \u001b[1msubprocess-exited-with-error\u001b[0m\n",
      "  \n",
      "  \u001b[31m×\u001b[0m \u001b[32mRunning setup.py install for tensorflow-gpu\u001b[0m did not run successfully.\n",
      "  \u001b[31m│\u001b[0m exit code: \u001b[1;36m1\u001b[0m\n",
      "  \u001b[31m╰─>\u001b[0m \u001b[31m[18 lines of output]\u001b[0m\n",
      "  \u001b[31m   \u001b[0m Traceback (most recent call last):\n",
      "  \u001b[31m   \u001b[0m   File \"<string>\", line 2, in <module>\n",
      "  \u001b[31m   \u001b[0m   File \"<pip-setuptools-caller>\", line 34, in <module>\n",
      "  \u001b[31m   \u001b[0m   File \"/private/var/folders/13/3pzxxwtd6cbdvdzq_lc6112r0000gn/T/pip-install-_m62r8yt/tensorflow-gpu_022857d31281414887364a2ec393f1e8/setup.py\", line 37, in <module>\n",
      "  \u001b[31m   \u001b[0m     raise Exception(TF_REMOVAL_WARNING)\n",
      "  \u001b[31m   \u001b[0m Exception:\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m =========================================================\n",
      "  \u001b[31m   \u001b[0m The \"tensorflow-gpu\" package has been removed!\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m Please install \"tensorflow\" instead.\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m Other than the name, the two packages have been identical\n",
      "  \u001b[31m   \u001b[0m since TensorFlow 2.1, or roughly since Sep 2019. For more\n",
      "  \u001b[31m   \u001b[0m information, see: pypi.org/project/tensorflow-gpu\n",
      "  \u001b[31m   \u001b[0m =========================================================\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m \u001b[31m[end of output]\u001b[0m\n",
      "  \n",
      "  \u001b[1;35mnote\u001b[0m: This error originates from a subprocess, and is likely not a problem with pip.\n",
      "\u001b[?25h\u001b[1;31merror\u001b[0m: \u001b[1mlegacy-install-failure\u001b[0m\n",
      "\n",
      "\u001b[31m×\u001b[0m Encountered error while trying to install package.\n",
      "\u001b[31m╰─>\u001b[0m tensorflow-gpu\n",
      "\n",
      "\u001b[1;35mnote\u001b[0m: This is an issue with the package mentioned above, not pip.\n",
      "\u001b[1;36mhint\u001b[0m: See above for output from the failure.\n",
      "\n",
      "\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m A new release of pip available: \u001b[0m\u001b[31;49m22.3.1\u001b[0m\u001b[39;49m -> \u001b[0m\u001b[32;49m24.0\u001b[0m\n",
      "\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m To update, run: \u001b[0m\u001b[32;49mpip install --upgrade pip\u001b[0m\n"
     ]
    }
   ],
   "source": [
    "!pip install labelme tensorflow tensorflow-gpu opencv-python matplotlib albumentations"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import time\n",
    "import uuid\n",
    "import cv2\n",
    "from matplotlib import pyplot as plt\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "IMAGES_PATH = os.path.join('data', 'images')\n",
    "number_images = 30"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting image 0\n",
      "Collecting image 1\n",
      "Collecting image 2\n",
      "Collecting image 3\n",
      "Collecting image 4\n",
      "Collecting image 5\n",
      "Collecting image 6\n",
      "Collecting image 7\n",
      "Collecting image 8\n",
      "Collecting image 9\n",
      "Collecting image 10\n",
      "Collecting image 11\n",
      "Collecting image 12\n",
      "Collecting image 13\n",
      "Collecting image 14\n",
      "Collecting image 15\n",
      "Collecting image 16\n",
      "Collecting image 17\n",
      "Collecting image 18\n",
      "Collecting image 19\n",
      "Collecting image 20\n",
      "Collecting image 21\n",
      "Collecting image 22\n",
      "Collecting image 23\n",
      "Collecting image 24\n",
      "Collecting image 25\n",
      "Collecting image 26\n",
      "Collecting image 27\n",
      "Collecting image 28\n",
      "Collecting image 29\n"
     ]
    },
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31mDer Kernel ist beim Ausführen von Code in der aktuellen Zelle oder einer vorherigen Zelle abgestürzt. \n",
      "\u001b[1;31mBitte überprüfen Sie den Code in der/den Zelle(n), um eine mögliche Fehlerursache zu identifizieren. \n",
      "\u001b[1;31mKlicken Sie <a href='https://aka.ms/vscodeJupyterKernelCrash'>hier</a>, um weitere Informationen zu erhalten. \n",
      "\u001b[1;31mWeitere Informationen finden Sie unter Jupyter <a href='command:jupyter.viewOutput'>Protokoll</a>."
     ]
    }
   ],
   "source": [
    "cap = cv2.VideoCapture(0)\n",
    "for imgnum in range(number_images):\n",
    "    print('Collecting image {}'.format(imgnum))\n",
    "    ret, frame = cap.read()\n",
    "    img_name = os.path.join(IMAGES_PATH, f'str{(uuid.uuid1())}.jpg')\n",
    "    cv2.imwrite(img_name, frame)\n",
    "    cv2.imshow('frame', frame)\n",
    "    time.sleep(0.5)\n",
    "\n",
    "    if cv2.waitKey(1) & 0xFF == ord('q'):\n",
    "        break\n",
    "\n",
    "cap.release()\n",
    "cv2.destroyAllWindows()\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting labelme\n",
      "  Using cached labelme-5.4.1-py3-none-any.whl\n",
      "Requirement already satisfied: gdown in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (from labelme) (5.1.0)\n",
      "Collecting PyYAML\n",
      "  Using cached PyYAML-6.0.1-cp310-cp310-macosx_11_0_arm64.whl (169 kB)\n",
      "Collecting imgviz>=1.7.5\n",
      "  Using cached imgviz-1.7.5-py3-none-any.whl\n",
      "Collecting qtpy!=1.11.2\n",
      "  Using cached QtPy-2.4.1-py3-none-any.whl (93 kB)\n",
      "Collecting onnxruntime!=1.16.0,>=1.14.1\n",
      "  Using cached onnxruntime-1.17.3-cp310-cp310-macosx_11_0_universal2.whl (14.8 MB)\n",
      "Requirement already satisfied: termcolor in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (from labelme) (2.4.0)\n",
      "Requirement already satisfied: Pillow>=2.8 in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (from labelme) (10.3.0)\n",
      "Collecting scikit-image\n",
      "  Using cached scikit_image-0.23.2-cp310-cp310-macosx_12_0_arm64.whl (13.3 MB)\n",
      "Collecting natsort>=7.1.0\n",
      "  Using cached natsort-8.4.0-py3-none-any.whl (38 kB)\n",
      "Requirement already satisfied: numpy in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (from labelme) (1.26.4)\n",
      "Requirement already satisfied: matplotlib in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (from labelme) (3.8.4)\n",
      "Collecting PyQt5!=5.15.3,!=5.15.4\n",
      "  Using cached PyQt5-5.15.10-cp37-abi3-macosx_11_0_arm64.whl (6.6 MB)\n",
      "Collecting coloredlogs\n",
      "  Using cached coloredlogs-15.0.1-py2.py3-none-any.whl (46 kB)\n",
      "Requirement already satisfied: flatbuffers in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (from onnxruntime!=1.16.0,>=1.14.1->labelme) (24.3.25)\n",
      "Collecting sympy\n",
      "  Using cached sympy-1.12-py3-none-any.whl (5.7 MB)\n",
      "Requirement already satisfied: packaging in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (from onnxruntime!=1.16.0,>=1.14.1->labelme) (24.0)\n",
      "Requirement already satisfied: protobuf in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (from onnxruntime!=1.16.0,>=1.14.1->labelme) (4.25.3)\n",
      "Requirement already satisfied: PyQt5-Qt5>=5.15.2 in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (from PyQt5!=5.15.3,!=5.15.4->labelme) (5.15.13)\n",
      "Collecting PyQt5-sip<13,>=12.13\n",
      "  Using cached PyQt5_sip-12.13.0-cp310-cp310-macosx_10_9_universal2.whl (144 kB)\n",
      "Requirement already satisfied: beautifulsoup4 in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (from gdown->labelme) (4.12.3)\n",
      "Requirement already satisfied: filelock in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (from gdown->labelme) (3.13.4)\n",
      "Requirement already satisfied: requests[socks] in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (from gdown->labelme) (2.31.0)\n",
      "Requirement already satisfied: tqdm in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (from gdown->labelme) (4.66.2)\n",
      "Requirement already satisfied: python-dateutil>=2.7 in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (from matplotlib->labelme) (2.9.0.post0)\n",
      "Requirement already satisfied: cycler>=0.10 in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (from matplotlib->labelme) (0.12.1)\n",
      "Requirement already satisfied: kiwisolver>=1.3.1 in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (from matplotlib->labelme) (1.4.5)\n",
      "Requirement already satisfied: pyparsing>=2.3.1 in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (from matplotlib->labelme) (3.1.2)\n",
      "Requirement already satisfied: contourpy>=1.0.1 in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (from matplotlib->labelme) (1.2.1)\n",
      "Requirement already satisfied: fonttools>=4.22.0 in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (from matplotlib->labelme) (4.51.0)\n",
      "Collecting lazy-loader>=0.4\n",
      "  Using cached lazy_loader-0.4-py3-none-any.whl (12 kB)\n",
      "Collecting imageio>=2.33\n",
      "  Using cached imageio-2.34.0-py3-none-any.whl (313 kB)\n",
      "Collecting networkx>=2.8\n",
      "  Using cached networkx-3.3-py3-none-any.whl (1.7 MB)\n",
      "Collecting scipy>=1.9\n",
      "  Using cached scipy-1.13.0-cp310-cp310-macosx_12_0_arm64.whl (30.3 MB)\n",
      "Requirement already satisfied: tifffile>=2022.8.12 in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (from scikit-image->labelme) (2024.4.18)\n",
      "Requirement already satisfied: six>=1.5 in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (from python-dateutil>=2.7->matplotlib->labelme) (1.16.0)\n",
      "Requirement already satisfied: soupsieve>1.2 in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (from beautifulsoup4->gdown->labelme) (2.5)\n",
      "Collecting humanfriendly>=9.1\n",
      "  Using cached humanfriendly-10.0-py2.py3-none-any.whl (86 kB)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (from requests[socks]->gdown->labelme) (3.7)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (from requests[socks]->gdown->labelme) (3.3.2)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (from requests[socks]->gdown->labelme) (2.2.1)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (from requests[socks]->gdown->labelme) (2024.2.2)\n",
      "Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (from requests[socks]->gdown->labelme) (1.7.1)\n",
      "Requirement already satisfied: mpmath>=0.19 in /Users/riccardo/Desktop/Repositorys_Github/Python_Face_Recognition/face/lib/python3.10/site-packages (from sympy->onnxruntime!=1.16.0,>=1.14.1->labelme) (1.3.0)\n",
      "Installing collected packages: sympy, scipy, qtpy, PyYAML, PyQt5-sip, networkx, natsort, lazy-loader, imageio, humanfriendly, scikit-image, PyQt5, coloredlogs, onnxruntime, imgviz, labelme\n",
      "Successfully installed PyQt5-5.15.10 PyQt5-sip-12.13.0 PyYAML-6.0.1 coloredlogs-15.0.1 humanfriendly-10.0 imageio-2.34.0 imgviz-1.7.5 labelme-5.4.1 lazy-loader-0.4 natsort-8.4.0 networkx-3.3 onnxruntime-1.17.3 qtpy-2.4.1 scikit-image-0.23.2 scipy-1.13.0 sympy-1.12\n",
      "\n",
      "\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m A new release of pip available: \u001b[0m\u001b[31;49m22.3.1\u001b[0m\u001b[39;49m -> \u001b[0m\u001b[32;49m24.0\u001b[0m\n",
      "\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m To update, run: \u001b[0m\u001b[32;49mpip install --upgrade pip\u001b[0m\n"
     ]
    }
   ],
   "source": [
    "!pip install labelme"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2024-04-21 13:52:54,702 [\u001b[1m\u001b[97mINFO   \u001b[0m] \u001b[36m__init__\u001b[0m:\u001b[36mget_config\u001b[0m:\u001b[36m67\u001b[0m- \u001b[1m\u001b[97mLoading config file from: /Users/riccardo/.labelmerc\u001b[0m\n"
     ]
    }
   ],
   "source": [
    "!labelme"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "face",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
